os: linux
dist: bionic
language: php

services:
  - docker

stage: Build Docker Images
env:
  - PHP_BUILD_VERSION=8.0
  - PHP_BUILD_VERSION=7.4
  - PHP_BUILD_VERSION=7.3
  - PHP_BUILD_VERSION=7.2
  - PHP_BUILD_VERSION=7.1
    
script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "$DOCKER_HUB_TOKEN" | docker login -u larueli --password-stdin && PUSH="--push"; fi
  - docker build --build-arg PHP_BUILD_VERSION=${PHP_BUILD_VERSION} -t larueli/php-base-image:${PHP_BUILD_VERSION} .
  - if [ ! -z $PUSH ]; then docker push larueli/php-base-image:${PHP_BUILD_VERSION}; fi
        
jobs:
  include:
    - stage: Deploy
      if: type != pull_request AND branch = master
      env:
        - PHP_BUILD_VERSION=7.4
      script:
        - echo "$DOCKER_HUB_TOKEN" | docker login -u larueli --password-stdin
        - docker pull larueli/php-base-image:7.4
        - docker tag larueli/php-base-image:7.4 larueli/php-base-image:latest
        - docker push larueli/php-base-image:latest
