os: linux
dist: bionic
language: php

env:
  - PHP_BUILD_VERSION=7.4
  - PHP_BUILD_VERSION=7.3

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install qemu-user-static
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
  - docker buildx inspect --bootstrap

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "$DOCKER_HUB_TOKEN" | docker login -u larueli --password-stdin && PUSH="--push"; fi
  - docker buildx build $PUSH --platform linux/arm64/v8,linux/amd64 --build-arg PHP_BUILD_VERSION=${PHP_BUILD_VERSION} -t larueli/php-base-image:${PHP_BUILD_VERSION} .

jobs:
  include:
    - stage: Deploy
      if: type != pull_request
      skip_cleanup: true
      env:
        - PHP_BUILD_VERSION=7.4
      script:
        - echo "$DOCKER_HUB_TOKEN" | docker login -u larueli --password-stdin
        - docker pull larueli/php-base-image:7.4
        - docker tag larueli/php-base-image:7.4 larueli/php-base-image:latest
        - docker push larueli/php-base-image:latest