os: linux
dist: bionic
language: php

arch:
  - amd64
  - arm64

env:
  - PHP_BUILD_VERSION=7.4
  - PHP_BUILD_VERSION=7.3
  - PHP_BUILD_VERSION=7.2
  - PHP_BUILD_VERSION=7.1

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker build --build-arg PHP_BUILD_VERSION=${PHP_BUILD_VERSION} -t larueli/php-base-image:${PHP_BUILD_VERSION} .
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "$DOCKER_HUB_TOKEN" | docker login -u larueli --password-stdin; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push larueli/php-base-image:${PHP_BUILD_VERSION}; fi